name: Deploy to Azure web app

on:
  workflow_run:
    workflows: ["Build and push Docker image"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: better-weather

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Configure Azure web app to use Docker image
        run: |
          az webapp config container set \
            --name ${{ env.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP}} \
            --docker-custom-image-name daefron/better-weather:latest \
            --docker-registry-server-url https://index.docker.io \
            --docker-registry-server-user ${{ secrets.DOCKER_HUB_USERNAME }} \
            --docker-registry-server-password ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Restart Azure Web App
        run: |
          az webapp restart --name ${{ env.AZURE_WEBAPP_NAME }} --resource-group ${{ secrets.AZURE_RESOURCE_GROUP}}
